[package]
name = "uu_tty"
version = "0.0.8"
authors = ["uutils developers"]
license = "MIT"
description = "tty ~ (uutils) display the name of the terminal connected to standard input"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/tty"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/tty.rs"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
libc = "0.2.42"
atty = "0.2"
uucore = { version=">=0.0.10", package="uucore", path="../../uucore", features=["fs"] }
uucore_procs = { version=">=0.0.7", package="uucore_procs", path="../../uucore_procs" }

[[bin]]
name = "tty"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["uucore_procs"]
