[package]
name = "uu_uniq"
version = "0.0.8"
authors = ["uutils developers"]
license = "MIT"
description = "uniq ~ (uutils) filter identical adjacent lines from input"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/uniq"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/uniq.rs"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
strum = "0.21"
strum_macros = "0.21"
uucore = { version=">=0.0.10", package="uucore", path="../../uucore" }
uucore_procs = { version=">=0.0.7", package="uucore_procs", path="../../uucore_procs" }

[[bin]]
name = "uniq"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["uucore_procs"]
