[package]
name = "uu_cp"
version = "0.0.8"
authors = [
    "Jordy Dickinson <jordy.dickinson@gmail.com>",
    "Joshua S. Miller <jsmiller@uchicago.edu>",
    "uutils developers",
]
license = "MIT"
description = "cp ~ (uutils) copy SOURCE to DESTINATION"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/cp"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/cp.rs"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
filetime = "0.2"
libc = "0.2.85"
quick-error = "1.2.3"
selinux = { version="0.2.3", optional=true }
uucore = { version=">=0.0.10", package="uucore", path="../../uucore", features=["entries", "fs", "perms", "mode"] }
uucore_procs = { version=">=0.0.7", package="uucore_procs", path="../../uucore_procs" }
walkdir = "2.2"

[target.'cfg(target_os = "linux")'.dependencies]
ioctl-sys = "0.6"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version="0.3", features=["fileapi"] }

[target.'cfg(unix)'.dependencies]
xattr="0.2.1"
exacl= { version = "0.6.0", optional=true }

[[bin]]
name = "cp"
path = "src/main.rs"

[features]
feat_selinux = ["selinux"]
feat_acl = ["exacl"]

[package.metadata.cargo-udeps.ignore]
normal = ["uucore_procs"]
