[package]
name = "uu_uptime"
version = "0.0.8"
authors = ["uutils developers"]
license = "MIT"
description = "uptime ~ (uutils) display dynamic system information"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/uptime"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/uptime.rs"

[dependencies]
chrono = "0.4"
clap = { version = "2.33", features = ["wrap_help"] }
uucore = { version=">=0.0.10", package="uucore", path="../../uucore", features=["libc", "utmpx"] }
uucore_procs = { version=">=0.0.7", package="uucore_procs", path="../../uucore_procs" }

[[bin]]
name = "uptime"
path = "src/main.rs"
