[package]
name = "uu_whoami"
version = "0.0.8"
authors = ["uutils developers"]
license = "MIT"
description = "whoami ~ (uutils) display user name of current effective user ID"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/whoami"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/whoami.rs"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
uucore = { version=">=0.0.10", package="uucore", path="../../uucore", features=["entries"] }
uucore_procs = { version=">=0.0.7", package="uucore_procs", path="../../uucore_procs" }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["lmcons"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.42"

[[bin]]
name = "whoami"
path = "src/main.rs"
