[package]
name = "uu_who"
version = "0.0.8"
authors = ["uutils developers"]
license = "MIT"
description = "who ~ (uutils) display information about currently logged-in users"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/who"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/who.rs"

[dependencies]
uucore = { version=">=0.0.10", package="uucore", path="../../uucore", features=["utmpx"] }
uucore_procs = { version=">=0.0.7", package="uucore_procs", path="../../uucore_procs" }
clap = { version = "2.33", features = ["wrap_help"] }

[[bin]]
name = "who"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["uucore_procs"]
